# pytorch_lightning==1.8.5.post0
seed_everything: true
trainer:
  logger: true
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 1
  accelerator: gpu
  strategy: ddp
  sync_batchnorm: true
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
ckpt_path: null
model:
  class_path: lightning.waveform.WaveformSeparator
  init_args:
    model: 
      class_path: torchaudio.models.HDemucs
      init_args:
        sources:
        - vocals
        - drums
        - bass
        - other
        channels: 48
    criterion: 
      class_path: loss.time.L1Loss
    apply_transforms: true
    targets: {vocals, drums, bass, other}
data:
  class_path: lightning.data.MUSDB
  init_args:
    root: /import/c4dm-datasets-ext/musdb18hq/
    seq_duration: 10.0
    samples_per_track: 500
    random: true
    random_track_mix: true
    apply_transforms: true
    batch_size: 4
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0003